name: Deploy (Build + FTP)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ftp-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Build & Enviar via FTP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies & build (Vite)
        run: |
          npm ci --no-audit --no-fund
          npm run build
        env:
          CI: true

      - name: Deploy FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./
          server-dir: ${{ secrets.FTP_PATH || 'laravel/' }}
          timeout: 60000
          exclude: |
            **/.git*
            **/.github/**
            node_modules/**
            tests/**
            storage/framework/cache/**
            storage/framework/sessions/**
            storage/framework/views/**
            vendor/**
            public/hot
            **/npm-debug.log
            **/yarn-error.log
            *.log
            *.tar.gz
          log-level: standard
          security: loose
          dry-run: false

      - name: Finalização
        run: echo "✅ Deploy FTP concluído (arquivos enviados)."

      - name: Aviso vendor (se excluído)
        if: always()
        run: |
          echo "Se precisar atualizar dependências PHP, rode 'composer install --no-dev -o' manualmente no servidor."
