name: Deploy Laravel via FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar FTP Action
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ftp.sienna-wolf-712626.hostingersite.com
          username: u834385447.grow
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./laravel
          server-dir: /home/u834385447/domains/sienna-wolf-712626.hostingersite.com/laravel
