name: Deploy (Build + SFTP)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ftp-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
  name: Build & Enviar via SFTP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies & build (Vite)
        run: |
          npm ci --no-audit --no-fund
          npm run build
        env:
          CI: true

      - name: Deploy SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          port: ${{ secrets.SFTP_PORT || 22 }}
          # Use ONE of password or ssh_private_key
          password: ${{ secrets.SFTP_PASSWORD }}
          # ssh_private_key: ${{ secrets.SFTP_SSH_KEY }}
          local_path: './'
          remote_path: ${{ secrets.SFTP_PATH }}/
          sftp_only: true
          args: '-o StrictHostKeyChecking=no'
          exclude: |
            .git*
            .github/**
            node_modules/**
            tests/**
            storage/framework/cache/**
            storage/framework/sessions/**
            storage/framework/views/**
            vendor/**
            *.log
            *.tar.gz
            public/hot
            **/npm-debug.log
            **/yarn-error.log

      - name: Finalização
        run: echo "✅ Deploy SFTP concluído (arquivos enviados)."

      - name: Aviso vendor (se excluído)
        if: always()
        run: |
          echo "Se precisar atualizar dependências PHP, rode 'composer install --no-dev -o' manualmente no servidor." 