name: Deploy Laravel with lftp

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build (opcional)
        working-directory: ./laravel
        run: |
          composer install --no-dev --optimize-autoloader
          npm ci
          npm run build

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Upload with lftp
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USERNAME }}
          FTP_PASS: ${{ secrets.FTP_PASSWORD }}
          TARGET_DIR: ${{ secrets.FTP_TARGET }}
        run: |
          # Se quiser SFTP, troque "ftp" por "sftp" em `set sftp:connect-program` ou use URL sftp://
          lftp -u "$FTP_USER","$FTP_PASS" "$FTP_HOST" -e "
            mirror -R --delete --verbose ./laravel $TARGET_DIR
            bye
          "
